#server:
#  port: 8088
#
#spring:
#  zipkin:
#    base-url: http://zipkin-server/
#  sleuth:
#    sampler:
#      probability: 1
#  application:
#    name: ribbon-rest
#
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8081/eureka/