spring:
 application:
  name: eureka-server
eureka:
  instance:
    prefer-ip-address: true
  server:
    enable-self-preservation: false
---
spring:
  profiles: eureka-server-1
server:
   port: 8081
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8082/eureka/,http://localhost:8083/eureka/
---
spring:
  profiles: eureka-server-2
server:
   port: 8082
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/,http://localhost:8083/eureka/
---
spring:
  profiles: eureka-server-3
server:
   port: 8083
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/,http://localhost:8082/eureka/